[package]
name = "secret-loader"
version = "0.0.1"
license = "MIT OR Apache-2.0"
edition = "2018"
resolver = "2"

authors = [
	"Eashwar Ranganathan <eashwar@eashwar.com>",
]

[dependencies]
camino = "1"
secrecy = "0.8"
serde = { version = "1", optional = true }
