name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  lint:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: cache dependencies
        uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --files-with-diff

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test MSRV and latest
        rust-version: [ 1.51, stable ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
      - name: cache dependencies
        uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: Build base library
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Build all features and targets
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --all-targets
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
